workflows:
  build_and_notify:
    name: Build APK and Send to Telegram
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build APK (split-per-abi)
        script: flutter build apk --split-per-abi

      - name: Send APK (armeabi-v7a) to Telegram
        script: |
          curl -F document=@build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk \
               -F chat_id=$TELEGRAM_CHAT_ID \
               -F caption="✅ APK (armeabi-v7a) جاهز 🔧" \
               https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument

      - name: Send APK (arm64-v8a) to Telegram
        script: |
          curl -F document=@build/app/outputs/flutter-apk/app-arm64-v8a-release.apk \
               -F chat_id=$TELEGRAM_CHAT_ID \
               -F caption="✅ APK (arm64-v8a) جاهز 🚀" \
               https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument
